### ISSUE TITLE
Icons of units are black squares.

### ISSUE THREAD

**Issue by BrnoPCmaniak** [Legion-Expansion/Legion-Expansion#543] opened 2016-07-22 22:31 UTC
I'm playing on linux everything good except the icons.
![screenshot from 2016-07-23 00-30-40](https://cloud.githubusercontent.com/assets/1249759/17072955/b52c78ba-506c-11e6-988a-495ddf438a29.png)

**Comment by Stuart1998** [comment] 2016-07-22 23:52
Duplicate of #489.

**Closed by Stuart1998** 2016-07-22 23:52 UTC
