### ISSUE TITLE
Multiple Legion into buttons when mod installed offline

### ISSUE THREAD

**Issue by Quitch** [Legion-Expansion/Legion-Expansion#569] opened 2017-06-26 10:15 UTC
**Steps to reproduce**

1. Create a PA shortcut with the launch option --localstorageurl=legion-bug-intro
2. Launch PA using this shortcut
3. Go into Community Mods and install Legion Expansion
4. Return to the main menu

**Actual results**

The top-left area has four buttons: Sign-in, Legion Intro, Create Account, Legion Intro. These will be here every time the player if offline.

<img width="256" alt="buttons" src="https://user-images.githubusercontent.com/5182715/27534967-b1c8427c-5a60-11e7-85a8-ec35f77a764b.png">

**Expected results**

Buttons for Sign-in and Create Account only

**Comment by Stuart1998** [comment] 2017-06-26 10:37
Does this bug matter? Like, when will it come up?

**Comment by Quitch** [comment] 2017-06-26 10:38
In the situation described in the steps i.e. new player installs it offline.

**Comment by domdom** [comment] 2017-06-26 11:33
So the expected behaviour is for there to be no Legion Intro button there in offline mode?

**Comment by Quitch** [comment] 2017-06-26 11:35
Ah, my bad. In all scenarios the Legion Intro button always correctly appears **at the bottom of the menu** i.e. where the standard intro button also appears.

**Comment by domdom** [comment] 2017-06-26 11:36
Ahh okay, thank you. I am having a look now :)

**Comment by domdom** [comment] 2017-06-26 11:43
Okay, the issue is that actually for pa, they have the view_intro class added to those two buttons as well, so the jquery selector does not uniquely identify the expected div.

**Comment by domdom** [comment] 2017-06-26 11:53
(It is untested btw, I will hop onto my computer now though)

**Comment by domdom** [comment] 2017-06-26 12:48
Tested and merged into balance.

**Closed** 2017-06-26 12:47 UTC
Labels: bug, ui

**Comment by Quitch** [comment] 2017-06-26 13:48
Thanks, dom!
