### ISSUE TITLE
Orbital Wraith

### ISSUE THREAD

**Issue by Qzipco** [Legion-Expansion/Legion-Expansion#264] opened 2016-02-29 18:10 UTC
The Wraith scout is Op compared to the sputnik. I think either it's health should be reduced to 700 and it's speed should also be reduced or raise the metal cost to 800-1000

**Comment by Stuart1998** [comment] 2016-02-29 20:32
Any orbital units currently in are placeholders, so this is a duplicate of #193.

**Closed by Stuart1998** 2016-02-29 20:32 UTC
Labels: duplicate
