### ISSUE TITLE
Commander no longer have blue command caps?

### ISSUE THREAD

**Issue by ksgrip** [Legion-Expansion/Legion-Expansion#487] opened 2016-05-07 17:15 UTC
![image](https://cloud.githubusercontent.com/assets/11367826/15093428/fbb08c48-1487-11e6-924c-861ccaa99253.png)

**Comment by Stuart1998** [comment] 2016-05-07 19:10
I think this was fixed, duplicate of #482

**Closed by Stuart1998** 2016-05-07 19:10 UTC
Labels: duplicate
