### ISSUE TITLE
Unit/Structure Icons are Black Boxes

### ISSUE THREAD

**Issue by cadenxh** [Legion-Expansion/Legion-Expansion#528] opened 2016-06-12 16:53 UTC
In place of normal labels for troops, ore deposits, buildings, or anything else, there is only a black box preventing sight of the item. This occurs with MLA  troops, ore deposits, buildings, etc also.

**Comment by Quitch** [comment] 2016-06-22 07:21
Duplicate of #489

**Closed by Quitch** 2016-06-22 07:21 UTC
Labels: duplicate
