### ISSUE TITLE
All Instances of metal texture usage need to be removed

### ISSUE THREAD

**Issue by nicb1** [Legion-Expansion/Legion-Expansion#531] opened 2016-06-15 07:23 UTC
Don't have a list but that old metal texture wherever present needs to be removed. Due to art-style and potential copyright concerns.

**Comment by Quitch** [comment] 2016-06-22 08:38
Changed milestone, this needs to be ready for v1

**Comment by Quitch** [comment] 2016-07-12 10:18
Duplicate of #530

**Closed by Quitch** 2016-07-12 10:18 UTC
Labels: duplicate, texture
